feat: switch to go-ora driver for oracle
CGI-FR/LINO pull request #165
Opened 2023-05-30 13:15 UTC by youen

2023-05-30 13:18 UTC, adrienaury commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
Peux tu ajouter l'alias "oracle" également ?

2023-05-30 13:18 UTC, adrienaury commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
```suggestion
		Aliases:   []string{"oracle-raw","oracle"},
```

2023-05-30 13:19 UTC, adrienaury commented on internal/app/urlbuilder/urlbuilder_test.go
>  			"oracle-raw://user:pwd@dbhost:1521/orclpdb1/?connect_timeout=2",
On perd la possibilité de passer `connect_timeout=2` ou autre option ?

2023-05-30 14:49 UTC, youen commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
Ce n'est pas si facile on dirait ...
 
```console
lino dc ping source
panic: scheme oracle already registered

goroutine 1 [running]:
github.com/xo/dburl.registerAlias({0xb5228d, 0xa}, {0xb4f846, 0x6}, 0x0)
        /home/vscode/go/pkg/mod/github.com/xo/dburl@v0.14.2/scheme.go:126 +0x28d
github.com/xo/dburl.Register({{0xb5228d, 0xa}, 0xbac570, 0x8, 0x0, {0xc00009d440, 0x2, 0x2}, {0xb4f846, 0x6}})
        /home/vscode/go/pkg/mod/github.com/xo/dburl@v0.14.2/scheme.go:170 +0x215
github.com/cgi-fr/lino/internal/app/urlbuilder.init.0()
        /workspace/internal/app/urlbuilder/urlbuilder.go:92 +0xd8
```

2023-05-30 14:52 UTC, adrienaury commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
Ok c'est déjà pris en charge par défaut par la librairie dburl : https://github.com/xo/dburl

A tester du coup ? si ça marche sans la spécification de l'alias ?

2023-05-30 19:22 UTC, youen commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
non ça ne marche pas : 

```
lino dc ping source -v 5
5:02PM INF Logger level set to trace
5:02PM INF Start LINO color=auto debug=false log-json=false verbosity=5
no datadestination found for database type
```

2023-05-31 07:44 UTC, adrienaury commented on internal/app/urlbuilder/urlbuilder.go
>  		Aliases:   []string{"oracle-raw"},
Tant pis, on traitera ce point plus tard ;)

2023-05-31 08:04 UTC, adrienaury approved these changes

2023-06-15 08:34 UTC, adrienaury requested changes
TODO: compile of lino binary should be done with CGO_ENABLED=0

- [ ] update CGO_ENABLED=0 in build.yml
- [x] update CGO_ENABLED=0 goreleaser.yml
- [ ] update CGO_ENABLED=0 in github actions
- [x] update CGO_ENABLED=0 in docker and docker-compose file
- [ ] update CGO_ENABLED=0 in devcontainer.json

2023-06-26 12:27 UTC, adrienaury approved these changes

2023-06-26 12:27 UTC, merged