feat(table) implements count command
CGI-FR/LINO pull request #67
Opened 2022-02-24 16:09 UTC by youen

2022-02-24 16:11 UTC, youen commented
output example :

```
lino table count source                             
inventory: 4581
payment: 16049
rental: 16044
staff: 2
actor: 200
customer: 599
film: 1000
film_category: 1000
store: 2
language: 6
category: 16
city: 600
film_actor: 5462
address: 603
country: 109
```

tables are not sort by name or size and list is randomized.

2022-02-25 15:02 UTC, adrienaury commented on internal/app/table/count.go
> +	cmd.Flags().StringVarP(&importType, "import", "i", "", "import type for the column")
Don't need these flags :)

2022-02-25 15:02 UTC, adrienaury commented on internal/app/table/count.go
> +	var exportType, importType string
Don't need these flags :)

2022-02-25 15:10 UTC, adrienaury commented
Lino didn't catch any HTTP 404 in my test

```console
❯ curl http://:@http-connector:8080/api/v1/data/actor/count
{"timestamp":"2022-02-25T15:09:59.296+00:00","status":404,"error":"Not Found","path":"/api/v1/data/actor/count"
❯ lino table count http -v5
4:07PM INF Logger level set to trace
4:07PM INF Start LINO color=auto debug=false log-json=false verbosity=5
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/actor/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/address/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/category/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/city/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/country/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/customer/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/film/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/film_actor/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/film_category/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/inventory/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/language/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/payment/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/rental/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/staff/count
4:07PM DBG External connector request url=http://:@http-connector:8080/api/v1/data/store/count
actor: 0
address: 0
category: 0
city: 0
country: 0
customer: 0
film: 0
film_actor: 0
film_category: 0
inventory: 0
language: 0
payment: 0
rental: 0
staff: 0
store: 0
4:07PM INF End LINO return=0
```

2022-02-25 15:13 UTC, adrienaury requested changes

2022-02-25 15:13 UTC, adrienaury commented on internal/infra/table/http_extractor.go
> +	container := struct {
You should check status code

```go
	if code < 200 || code >= 300 {
		return &push.Error{Description: fmt.Sprintf("HTTP request returned status code %d", code)}
	}
```

2022-02-25 15:21 UTC, youen commented
should we upgrade version's api to v2 ?

2022-02-25 15:46 UTC, adrienaury commented
> should we upgrade version's api to v2 ?

No, there is no changes in the api, only added feature

2022-02-25 15:48 UTC, adrienaury approved these changes

2022-02-25 15:52 UTC, merged